#!/bin/bash
BASEDIR=$(dirname "$0")
cd $BASEDIR &&
/home/tom/Dropbox/Coding/Otohits/OtohitsApp/Linux/OtohitsApp/OtohitsViewer --no-sandbox eyJBIjoiTW96aWxsYS81LjAgKExpbnV4OyBBbmRyb2lkIDQuMy4xOyBHVC1ONzEwMCBCdWlsZC9KTFMzNkkpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS80OC4wLjI1NjQuMTE2IE1vYmlsZSBTYWZhcmkvNTM3LjM2IiwiQyI6MCwiREdMIjp0cnVlLCJIIjo2NzEwODg2NywiSEciOjAsIkkiOjEyNCwiSyI6InNpUDlhekZnWm1xUUJQd3N1V2tLNXp1b3NRdz0iLCJNIjoxNDc3MzE4MDIyLCJOTCI6ZmFsc2UsIlAiOjAsIlMiOjM5MDA3OCwiVSI6IiIsIlYiOnRydWUsIldEIjowfQ==
